language: node_js
notifications:
  email: false
node_js:
  - 9
branches:
  only:
    - master
    - /^greenkeeper.*$/
before_install:
  - cd docs && bundle install && cd ..
install:
  - travis_retry npm install
script:
  - npm run test
  - 'if [ "$SAUCE_ACCESS_KEY" != "false" ]; then npm run saucelabs; fi'
after_success:
  - npm run codecov
  - npm run semantic-release
