source 'https://rubygems.org'

gem 'jekyll', '~> 3.8.6'

group :jekyll_plugins do
   gem 'jekyll-github-metadata', '~> 2.12.1'
   gem 'jekyll-seo-tag', '~> 2.6.1'
   gem 'jekyll-sitemap', '~> 1.3.1'
   gem 'jekyll-octicons', '~> 9.2.0'
   gem 'nokogiri', '~> 1.11.4'
end
