source 'https://rubygems.org'

gem 'jekyll', '~> 3.5.2'

group :jekyll_plugins do
   gem 'jekyll-github-metadata', '~> 2.9.3'
   gem 'jekyll-seo-tag', '~> 2.3.0'
   gem 'jekyll-sitemap', '~> 1.1.1'
   gem 'jekyll-octicons', '~> 4.0.1'
   gem 'nokogiri', '~> 1.8.0'
end
