source 'https://rubygems.org'

gem 'jekyll', '~> 3.6.3'

group :jekyll_plugins do
   gem 'jekyll-github-metadata', '~> 2.9.4'
   gem 'jekyll-seo-tag', '~> 2.5.0'
   gem 'jekyll-sitemap', '~> 1.2.0'
   gem 'jekyll-octicons', '~> 8.1.0'
   gem 'nokogiri', '~> 1.8.5'
end
